# Generated by Django 5.2.4 on 2025-07-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_course_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image_url',
            new_name='cover_url',
        ),
        migrations.AddField(
            model_name='course',
            name='thmb',
            field=models.URLField(blank=True, max_length=90000),
        ),
    ]
