# Generated by Django 5.2.4 on 2025-08-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
